= Provides a JavaEE Event <--> RabbitMQ bridge.
Patrick Reinhart <https://github.com/reinhapa[@reinhapa]>
:project-full-path: reinhapa/rabbitmq-cdi
:github-branch: master

image:https://img.shields.io/badge/license-MIT-blue.svg["MIT License", link="https://github.com/{project-full-path}/blob/github-branch}/LICENSE"]
image:https://img.shields.io/badge/Java-8-blue.svg["Supported Versions", link="https://travis-ci.org/{project-full-path}"]
image:https://img.shields.io/travis/{project-full-path}/{github-branch}.svg["Build Status", link="https://travis-ci.org/{project-full-path}"]
image:https://img.shields.io/codecov/c/github/{project-full-path}/{github-branch}.svg["Code Coverage", link="https://codecov.io/github/{project-full-path}?branch={github-branch}"]

image:https://codecov.io/github/{project-full-path}/branch.svg?branch={github-branch}[codecov.io]

This project contains all needed classes to bind a JavaEE enterprise event to a
RabbitMQ exchange for outgoing events. Inbound events can also be bound on the
respective queues and will be hand over to all JavaEE event observers.

The RabbitMQ message content is done via JSON serialization of a Java Bean 
compatible PoJo object and vice versa.

## Usage example

First you need to define a event objects using standard Java Bean syntax:

[source,java]
----
public class EventOne {
  private boolean enabled;

  public boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(boolean enabled) {
    this.enabled = enabled;
  }
}

public class EventTwo {
  private String value;

  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }
}
----


As second step you have to define the bindings:

[source,java]
----
public class RabbitBinder extends EventBinder {
  @Override
  protected void bindEvents() {
    bind(EventOne.class).toExchange("test.from").withRoutingKey("test.key");
    bind(EventTwo.class).toQueue("test.queue");
  }
}
----

As last step you need to initialize the binder either within in a singleton
startup bean or servlet after having also configured the connection settings:

[source,java]
----
@Singleton
@Startup
public class BindingInitializer {
  @Inject
  private RabbitBinder binder;

  @PostConstruct
  public void initialize() {
    try {
      binder.configuration().setHost("somehost.somedomain").setUsername("myuser").setPassword("mypassword");
      binder.initialize();
    } catch (IOException e) {
      LoggerFactory.getLogger(getClass()).error("Unable to initialize", e);
    }
  }
}
----


Now the events can be used within your JavaEE 7 container:

[source,java]
----
public class EventDemoBean {
  @Inject
  private Event<EventOne> eventOnes;
  
  public void submitEvent(boolean enabled) {
    EventOne eventOne = new EventOne();
    eventOne.setEnabled(enabled);
    eventOnes.fire(eventOne);
  }

  public void reveiveEvent(@Observes EventTwo eventTwo) {
    String data = eventTwo.getData();
    // do some work
  }
}
----

